export enum AppPagePath {
  ROOT = '/',
  HOME = 'home',
  CONTACT = 'contact',
  ABOUT = 'about',
  SIGNIN = 'signin',
  SIGNUP = 'signup',
  SUCCESS = 'success',
  ACTIVATE_SUCCESS = 'signup/activate',
  NEW_CARD = '/new-card',
  INFORMATION = '/information',
  STUDENTS = '/students',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password/:id',
}
