export enum AppPagePath {
  ROOT = '/',
  HOME = 'home',
  CONTACT = 'contact',
  ABOUT = 'about',
  SIGNIN = 'signin',
  SIGNUP = 'signup',
  SUCCESS = 'success',
  ACTIVATE_SUCCESS = 'signup/activate/:id',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_PASSWORD = 'reset-password/:id',
  CARDS = 'cards',
  NEW_CARD = 'cards/new',
  INFORMATION = 'information',
  STUDENTS = 'students',
}
